"$schema" = "https://starship.rs/config-schema.json"

# globals
scan_timeout = 100
command_timeout = 500
follow_symlinks = false
add_newline = true
palette = "poimandres"

# formats
format = """
$directory \
$git_branch\
$git_state\
$git_status\
$status\
$cmd_duration\
$fill\
$kubernetes\
$line_break\
$character\
"""

[fill]
symbol = " "

# directory
[directory]
style = "fg:sapphire"
format = "[\ueaf7 $path]($style)"
truncation_length = 3
# truncation_symbol = "…/"
truncate_to_repo = true

# git
[git_branch]
symbol = "\uf418"
style = "fg:sky bg:surface1"
format = "[at ](overlay1)[\ueba1](text)[  on ](overlay1)[\ue0b6](surface1)[$symbol $branch(:$remote_branch)]($style)"

[git_state]
style = "fg:sky bg:surface1"
format = "[ \\($state( $progress_current/$progress_total)\\)]($style)"
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = "cherry-picking"
bisect = "bisecting"
am = "am"
am_or_rebase = "am/rebase"

[git_status]
style = "fg:red bg:surface1"
format = "([ $untracked$staged$modified$renamed$conflicted$ahead_behind]($style))[\ue0b4](surface1) "
staged     = "+${count}"
modified   = "!${count}"
renamed    = "\u00bb${count}"
deleted    = "-${count}"
untracked  = "?${count}"
stashed    = "\u2261${count}"
conflicted = "\u2716${count}"
ahead      = "\u21e1${count}"
behind     = "\u21e3${count}"
diverged   = "\u21d5\u21e1${ahead_count}\u21e3${behind_count}"

# misc
[status]
disabled = false
symbol = "\u2718"
success_symbol = "\uf46f"
format = "[$symbol]($style)"
success_style = "teal"
style = "red"
map_symbol = false

[cmd_duration]
min_time = 1000
format = "  [took ](subtext1)[$duration](yellow)"

[character]
success_symbol = "[❯](teal)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[:](mauve)"

# cloud / contexts
[kubernetes]
disabled = false
style = "bold #A78BFA"
symbol = "\ue81d"
format = "[$symbol $context(/$namespace)]($style)"

[aws]
disabled = false
style = "bold #FF9900"
symbol = "\ue7ad"
format = "[$symbol $profile ]($style)"

[azure]
disabled = false
style = "bold #0078D4"
symbol = "\uebd8"
format = "[$symbol $subscription ]($style)"

[gcloud]
disabled = false
style = "bold #EA4335"
symbol = "\U000F11F6"
format = "[$symbol $domain(/$project) ]($style)"

# palettes
[palettes.poimandres]
# --- background ---
crust    = "#171922"
mantle   = "#1B1E28"
base     = "#1B1E28"
surface0 = "#303340"
surface1 = "#3B4152"
surface2 = "#506477"
overlay0 = "#506477"
overlay1 = "#767C9D"
overlay2 = "#A6ACCD"
# --- text ---
text     = "#E4F0FB"
subtext0 = "#A6ACCD"
subtext1 = "#767C9D"
# --- accents ---
rosewater = "#FAE4FC"
flamingo  = "#FCC5E9"
pink      = "#FCC5E9"
mauve     = "#D0679D"
red       = "#D0679D"
maroon    = "#E4747C"
peach     = "#FFFAC2"
yellow    = "#FFFAC2"
green     = "#5DE4C7"
teal      = "#5DE4C7"
sky       = "#ADD7FF"
sapphire  = "#89DDFF"
blue      = "#89DDFF"
lavender  = "#91B4D5"
